# These are supported funding model platforms

github: # [jenniekibiri, zachydev]
patreon: #zachydev
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/testapi
community_bridge: testapi
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom:  ['https://github.com/zachydev', 'https://github.com/jenniekibiri']
